# Generated by Django 5.0.1 on 2024-02-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
